//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackTrip.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripSegment
    {
        public long SegmentID { get; set; }
        public Nullable<byte> SegmentType { get; set; }
        public string Topic { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<long> CostSeconds { get; set; }
        public string Posi { get; set; }
        public Nullable<int> Index { get; set; }
        public long TripID { get; set; }
    }
}
