//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackTrip.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripCollection
    {
        public long TripId { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string OriginPosi { get; set; }
        public string DestinationPosi { get; set; }
        public Nullable<System.DateTime> OriginTime { get; set; }
        public Nullable<System.DateTime> DestinationTime { get; set; }
        public string Topic { get; set; }
    }
}
